"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    'nav.about': 'Sobre Nós',
    'nav.solutions': 'SOLUÇÕES',
    'nav.contact': 'Contato',
    'nav.quote': 'Cotação Online',
    'nav.company': 'Empresa',
    'nav.people': 'Pessoas',
    'nav.forCompany': 'Para Empresa',
    'nav.forYou': 'Para Você',
    'sol.health': 'Saúde',
    'sol.life': 'Vida',
    'sol.dental': 'Odontológico',
    'sol.international': 'Internacional',
    'sol.person': 'Pessoa',
    'hero.title.business': 'Seguros para Empresas',
    'hero.desc.business': 'Consultoria personalizada para o seu negócio, com inovação e inteligência cibernética.',
    'hero.title.people': 'Seguros para Pessoas',
    'hero.desc.people': 'Proteção completa para você e sua família, com foco em cuidado elevado e tranquilidade.',
    'hero.learnMore': 'SABER MAIS',
    'about.badge': 'SOBRE NÓS',
    'about.title': 'Sua saúde merece um cuidado elevado.',
    'about.desc': 'A Sante é uma corretora de alta performance, entregando as melhores soluções em Seguro Saúde, Vida e Planos Internacionais com foco total em proteção e inovação há 20 anos.',
    'about.regional': 'Regional',
    'about.regional.desc': 'Melhores opções locais.',
    'about.national': 'Nacional',
    'about.national.desc': 'Cobertura em todo o país.',
    'about.global': 'Global',
    'about.global.desc': 'Atendimento pelo mundo.',
    'partners.badge': 'Rede de Excelência',
    'partners.title': 'Seguradoras Parceiras',
    'international.badge': 'Alcance Global',
    'international.title': 'Sua proteção não conhece fronteiras.',
    'international.desc': 'O cuidado Sante ultrapassa limites geográficos. Com a nossa solução VUMI Internacional, garantimos acesso aos centros médicos mais prestigiados do mundo.',
    'international.cta': 'Explorar VUMI',
    'international.families': '+500 Famílias Protegidas',
    'international.feature1': 'Segunda Opinião Médica',
    'international.feature2': 'Livre Escolha Mundial',
    'testimonials.badge': 'Depoimentos',
    'testimonials.title': 'A confiança de quem vive a diferença.',
    'testimonials.desc': 'Nossa maior recompensa é a tranquilidade dos nossos clientes. Veja o que dizem sobre o cuidado e a performance da Sante.',
    'contact.badge': 'Contato Prioritário',
    'contact.title': 'Fale com um especialista agora.',
    'contact.desc': 'Especialistas prontos para te atender.',
    'form.name': 'Nome completo',
    'form.name.placeholder': 'Como te chamamos?',
    'form.email': 'E-mail corporativo',
    'form.email.placeholder': 'contato@sante.com.br',
    'form.whatsapp': 'WhatsApp / Celular',
    'form.whatsapp.placeholder': '(11) 99999-9999',
    'form.message': 'Sua solicitação',
    'form.message.placeholder': 'Fale um pouco sobre o que você busca...',
    'form.submit': 'Enviar Proposta',
    'form.submitting': 'Enviando...',
    'form.success': '✓ Enviado com sucesso!',
    'form.error': '× Erro ao enviar. Tente novamente.',
    'form.privacy': 'Ao enviar, você concorda com nossa política de privacidade.',
    'footer.desc': 'Especialistas em proteção elevada. Oferecemos soluções inteligentes em seguros saúde, vida e planos internacionais com foco em excelência e cuidado.',
    'footer.solutions': 'Nossas Soluções',
    'footer.institutional': 'Institucional',
    'footer.contact': 'Fale Conosco',
    'footer.privacy': 'Privacidade',
    'footer.terms': 'Termos',
    'footer.tagline': 'Elevando o cuidado com inovação',
    'corp.badge': 'Seguros para Empresas',
    'corp.title': 'Proteção estratégica para o seu maior patrimônio.',
    'corp.desc': 'Consultoria personalizada e soluções robustas de saúde e proteção, desenhadas para empresas que buscam excelência e valorização do capital humano.',
    'corp.cta': 'SOLICITAR COTAÇÃO',
    'corp.partners': '+150 Empresas Parceiras',
    'corp.health.title': 'Saúde Empresarial',
    'corp.health.desc': 'O benefício mais valorizado pelos colaboradores. Oferecemos gestão eficiente, redução de custos e acesso às melhores redes hospitalares para sua equipe.',
    'corp.health.f1': 'Gestão de sinistralidade e BI para empresas',
    'corp.health.f2': 'Rede referenciada premium e atendimento exclusivo',
    'corp.health.f3': 'Modelos flexíveis com ou sem coparticipação',
    'corp.health.cta': 'ANALISAR MEU PLANO',
    'corp.life.title': 'Vida em Grupo',
    'corp.life.desc': 'Segurança para seus colaboradores e conformidade para sua empresa. Planos flexíveis que atendem convenções coletivas e protegem o futuro das famílias.',
    'corp.life.f1': 'Atendimento a convenções coletivas (CCT)',
    'corp.life.f2': 'Proteção financeira para colaboradores e sócios',
    'corp.life.f3': 'Assistências exclusivas e contratação simplificada',
    'corp.life.cta': 'SIMULAR BENEFÍCIO',
    'corp.dental.title': 'Odonto Empresarial',
    'corp.dental.desc': 'Bem-estar completo para seu time com custo reduzido. Uma rede ampla e atendimento ágil para garantir o melhor sorriso da sua empresa.',
    'corp.dental.f1': 'Baixo impacto no budget e alto valor percebido',
    'corp.dental.f2': 'Rede nacional com especialistas em todas as áreas',
    'corp.dental.f3': 'Contratação rápida a partir de 2 vidas (MEI)',
    'corp.dental.cta': 'COTAR AGORA',
    'corp.form.badge': 'Consultoria Corporativa',
    'corp.form.title': 'Otimize seus benefícios e proteja seu negócio.',
    'corp.form.desc': 'Preencha os dados da sua empresa e receba um estudo técnico personalizado dos nossos especialistas.',
    'ind.badge': 'Seguros para Pessoas',
    'ind.title': 'Proteção completa para você e sua família.',
    'ind.desc': 'Soluções personalizadas de saúde, vida e odontológico desenhadas para quem valoriza um cuidado elevado e tranquilidade em todos os momentos.',
    'ind.cta': 'SOLICITAR COTAÇÃO',
    'ind.lives': '+2.500 Vidas Protegidas',
    'ind.health.title': 'Plano de Saúde',
    'ind.health.desc': 'O cuidado que sua saúde merece, com acesso aos melhores hospitais e uma rede credenciada de excelência. Transparência e agilidade no atendimento.',
    'ind.health.f1': 'Cobertura médica completa e abrangente',
    'ind.health.f2': 'Rede hospitalar de alta performance',
    'ind.health.f3': 'Opções flexíveis com ou sem coparticipação',
    'ind.health.cta': 'COTAÇÃO RÁPIDA',
    'ind.life.title': 'Seguro de Vida',
    'ind.life.desc': 'Tranquilidade para quem você ama. Nosso seguro de vida oferece o suporte financeiro necessário para enfrentar imprevistos com segurança.',
    'ind.life.f1': 'Proteção financeira sólida para sua família',
    'ind.life.f2': 'Cobertura completa em casos de imprevistos',
    'ind.life.f3': 'Flexibilidade total na escolha de valores',
    'ind.life.cta': 'SIMULAR PROTEÇÃO',
    'ind.dental.title': 'Plano Odontológico',
    'ind.dental.desc': 'Um sorriso saudável é a porta de entrada para o bem-estar. Oferecemos planos com baixo custo e ampla rede credenciada.',
    'ind.dental.f1': 'Consultas, limpezas e procedimentos diversos',
    'ind.dental.f2': 'Rede credenciada em todo o território nacional',
    'ind.dental.f3': 'Excelente custo-benefício para você e dependentes',
    'ind.dental.cta': 'COTAÇÃO RÁPIDA',
    'ind.form.badge': 'Cotação Online',
    'ind.form.title': 'Inicie sua jornada para um cuidado elevado hoje.',
    'ind.form.desc': 'Preencha os dados abaixo e receba uma análise personalizada dos nossos especialistas.',
    'ind.form.quick': 'Atalho Rápido',
    'ind.form.quick.desc': 'Não quer preencher o formulário agora? Sem problemas! Envie uma mensagem rápida ou anexe seus documentos e entraremos em contato.',
    'ind.form.talk': 'Falar com Especialista',
    'ind.form.talk.desc': 'Solicite uma cotação pelo formulário de contato',
    'ind.form.upload': 'Enviar Arquivo',
    'ind.form.upload.desc': 'PDF, planilha ou qualquer documento',
    'ind.form.step1': 'Dados de Contato',
    'ind.form.step2': 'O que você busca?',
    'ind.form.step2.life': 'Detalhes Seguro de Vida',
    'ind.form.step3': 'Perfil da Contratação',
    'ind.form.step4': 'Preferências',
    'ind.form.step5': 'Necessidades',
    'ind.form.step6': 'Finalizar',
    'ind.form.files': 'Arquivos anexados:',
    'form.back': 'Voltar',
    'form.next': 'Próxima Etapa',
    'form.submitStudy': 'Enviar para Estudo',
    'form.successFull': '✓ Enviado com sucesso! Entraremos em contato.',
    'corp.form.step1.title': 'Dados da Empresa',
    'corp.form.step1.desc': 'Conte um pouco sobre o seu negócio para começarmos.',
    'corp.form.step2.title': 'O que sua empresa precisa?',
    'corp.form.step2.desc': 'Você pode selecionar mais de uma opção.',
    'corp.form.step3.title': 'Informações Gerais',
    'corp.form.step4.title': 'Perfil da Empresa',
    'corp.form.step5.title': 'Detalhes por Produto',
    'corp.form.step5.desc': 'Vamos customizar sua solicitação com base nas suas escolhas.',
    'corp.form.step6.title': 'Preferências Finais',
    'corp.form.upload.title': 'Upload de arquivo (Opcional)',
    'corp.form.upload.desc': 'Se você já possui uma planilha de vidas ou cotações anteriores, anexe aqui.',
    'corp.form.upload.optional': 'Documentos Opcionais',
    'mascot.label': 'DICA DO SANTÊ',
    'mascot.defaultMessage': 'Preencha o quanto quiser — quanto mais informações, mais precisa e personalizada será sua cotação',
    'wa.message': 'Olá! Quero solicitar uma cotação!',
    'cf.companyName': 'Nome da Empresa', 'cf.companyName.ph': 'Razão Social ou Fantasia',
    'cf.cnpj': 'CNPJ', 'cf.cnpj.ph': '00.000.000/0001-00',
    'cf.responsible': 'Nome do Responsável', 'cf.responsible.ph': 'Quem falará conosco?',
    'cf.email': 'E-mail Corporativo', 'cf.email.ph': 'rh@empresa.com.br',
    'cf.whatsapp': 'WhatsApp de Contato', 'cf.whatsapp.ph': '(11) 99999-9999',
    'cf.healthPlan': 'Plano de Saúde', 'cf.lifeInsurance': 'Seguro de Vida', 'cf.dentalPlan': 'Plano Odontológico',
    'cf.startDate': 'Data de início desejada',
    'cf.hasBenefit': 'A empresa já possui esse(s) benefício(s)?',
    'cf.yes': 'Sim', 'cf.no': 'Não', 'cf.which': 'Qual?',
    'cf.which.ph': 'Ex: SulAmérica Saúde, Bradesco Dental...',
    'cf.employees': 'Número de Colaboradores', 'cf.employees.ph': 'Ex: 50',
    'cf.cityState': 'Cidade / Estado', 'cf.cityState.ph': 'Ex: São Paulo / SP',
    'cf.segment': 'Segmento da Empresa', 'cf.segment.ph': 'Ex: Tecnologia, Indústria, Comércio...',
    'cf.noProducts': 'Você não selecionou nenhum produto no Passo 2.',
    'cf.life.title': 'Seguro de Vida', 'cf.life.coverageType': 'Tipo de Cobertura',
    'cf.life.perEmployee': 'Valor por Colaborador', 'cf.life.perEmployee.desc': 'Cada vida tem um capital segurado fixo.',
    'cf.life.global': 'Valor Global', 'cf.life.global.desc': 'Capital dividido entre os funcionários.',
    'cf.life.accidents': 'Acidentes Pessoais', 'cf.life.accidents.desc': 'Cobertura específica para acidentes.',
    'cf.life.spouses': 'Deseja incluir cônjuges?', 'cf.life.absent': 'Colaborador afastado?',
    'cf.life.capitalDef': 'Definição de Capital (Valor)', 'cf.life.selectOption': 'Selecione uma opção...',
    'cf.life.equalAll': 'Igual para todos', 'cf.life.salaryBased': 'Múltiplo Salarial (ex: 12x ou 24x)',
    'cf.life.byPosition': 'Diferenciado por cargo',
    'cf.health.title': 'Plano de Saúde', 'cf.health.samePlan': 'Todos os colaboradores no mesmo plano?',
    'cf.health.samePlan.note': 'Se "Não", dividiremos o grupo por categorias (ex: Diretoria vs. Operação).',
    'cf.health.accommodation': 'Tipo de Acomodação', 'cf.health.select': 'Selecione...',
    'cf.health.ward': 'Enfermaria (Coletivo)', 'cf.health.apartment': 'Apartamento (Individual)',
    'cf.health.copart': 'Coparticipação', 'cf.health.noCopart': 'Sem Coparticipação',
    'cf.health.withCopart': 'Com Coparticipação', 'cf.health.copartLimit': 'Limite de Coparticipação (%)',
    'cf.health.copartRecommend': 'Geralmente recomendado: 20% ou 30%.',
    'cf.dental.title': 'Odonto Empresarial', 'cf.dental.hasPlan': 'Já possui plano Odontológico?',
    'cf.dental.currentProvider': 'Qual a operadora atual?', 'cf.dental.currentProvider.ph': 'Ex: Amil Dental, OdontoPrev...',
    'cf.objective': 'Qual o principal objetivo com esta cotação?',
    'cf.reduceCosts': 'Reduzir Custos', 'cf.betterCoverage': 'Melhor Cobertura', 'cf.retainTalent': 'Reter Talentos',
    'cf.upgradeLevel': 'Nível de Upgrade Desejado',
    'cf.basic': 'Básico (Foco em preço)', 'cf.intermediate': 'Intermediário (Custo-benefício)',
    'cf.premium': 'Premium (Alta cobertura e reembolso)',
    'cf.additionalServices': 'Serviços Adicionais Desejados',
    'cf.reimbursement': 'Livre Escolha (Reembolso)', 'cf.concierge': 'Serviço de Concierge',
    'cf.airRescue': 'Resgate Aeromédico',
    'cf.hospitals': 'Hospitais ou Laboratórios Mandatórios?', 'cf.hospitals.ph': 'Ex: Albert Einstein, Sírio Libanês, Fleury...',
    'pf.step1': 'Dados de Contato', 'pf.fullName': 'Nome Completo', 'pf.fullName.ph': 'Seu nome',
    'pf.email': 'E-mail', 'pf.email.ph': 'seu@email.com',
    'pf.whatsapp': 'WhatsApp', 'pf.whatsapp.ph': '(11) 99999-9999',
    'pf.step2': 'O que você busca?',
    'pf.healthPlan': 'Plano de Saúde', 'pf.lifeInsurance': 'Seguro de Vida', 'pf.dentalPlan': 'Plano Odontológico',
    'pf.lifeDetails': 'Detalhes Seguro de Vida',
    'pf.dob': 'Data de Nascimento', 'pf.sex': 'Sexo', 'pf.select': 'Selecione...',
    'pf.male': 'Masculino', 'pf.female': 'Feminino',
    'pf.occupation': 'Ocupação', 'pf.occupation.ph': 'Ex: Engenheiro, Médico...',
    'pf.income': 'Faixa de Renda',
    'pf.step3': 'Perfil da Contratação', 'pf.planType': 'Tipo de Plano',
    'pf.individual': 'Individual', 'pf.family': 'Familiar',
    'pf.location': 'Localização', 'pf.location.ph': 'Cidade/Região',
    'pf.lives': 'Quantidade de Vidas', 'pf.lives.ph': 'Ex: 5',
    'pf.ages': 'Idade das pessoas', 'pf.ages.ph': 'Ex: 25, 30, 2',
    'pf.step4': 'Preferências', 'pf.copart': 'Coparticipação',
    'pf.indifferent': 'Indiferente', 'pf.yes': 'Sim', 'pf.no': 'Não',
    'pf.accommodation': 'Acomodação', 'pf.apartment': 'Apartamento', 'pf.ward': 'Enfermaria',
    'pf.coverage': 'Abrangência', 'pf.regional': 'Regional', 'pf.national': 'Nacional', 'pf.international': 'Internacional',
    'pf.priority': 'O que é mais importante para você?',
    'pf.lowCost': 'Mensalidade baixa', 'pf.bestNetwork': 'Melhor rede hospitalar', 'pf.costQuality': 'Custo x Qualidade',
    'pf.hospitals': 'Hospitais que não podem faltar', 'pf.hospitals.ph': 'Ex: Albert Einstein, Sírio-Libanês, etc...',
    'pf.step5': 'Necessidades', 'pf.frequency': 'Frequência de uso',
    'pf.low': 'Baixa', 'pf.medium': 'Média', 'pf.high': 'Alta',
    'pf.desiredCoverage': 'Coberturas desejadas',
    'pf.therapy': 'Terapia', 'pf.physio': 'Fisioterapia', 'pf.maternity': 'Maternidade',
    'pf.step6': 'Finalizar', 'pf.upload': 'Upload de arquivo (Opcional)',
    'pf.upload.desc': 'Se você for MEI ou possuir várias vidas, anexe um PDF ou Planilha.',
    'pf.files': 'Arquivos anexados:',
    'pf.importantNote': 'Algo importante que devemos saber?', 'pf.importantNote.ph': 'Sua mensagem...',
    'pf.submitAnalysis': 'Enviar para análise'
  },
  en: {
    'nav.about': 'About Us',
    'nav.solutions': 'SOLUTIONS',
    'nav.contact': 'Contact',
    'nav.quote': 'Online Quote',
    'nav.company': 'Company',
    'nav.people': 'People',
    'nav.forCompany': 'For Business',
    'nav.forYou': 'For You',
    'sol.health': 'Health',
    'sol.life': 'Life',
    'sol.dental': 'Dental',
    'sol.international': 'International',
    'sol.person': 'Individual',
    'hero.title.business': 'Insurance for Businesses',
    'hero.desc.business': 'Personalized consultancy for your business, with innovation and cyber intelligence.',
    'hero.title.people': 'Insurance for Individuals',
    'hero.desc.people': 'Complete protection for you and your family, focusing on elevated care and peace of mind.',
    'hero.learnMore': 'LEARN MORE',
    'about.badge': 'ABOUT US',
    'about.title': 'Your health deserves elevated care.',
    'about.desc': 'Sante is a high-performance brokerage, delivering the best solutions in Health, Life, and International Insurance with a total focus on protection and innovation for 20 years.',
    'about.regional': 'Regional',
    'about.regional.desc': 'Best local options.',
    'about.national': 'National',
    'about.national.desc': 'Country-wide coverage.',
    'about.global': 'Global',
    'about.global.desc': 'Service around the world.',
    'partners.badge': 'Network of Excellence',
    'partners.title': 'Partner Insurance Companies',
    'international.badge': 'Global Reach',
    'international.title': 'Your protection knows no borders.',
    'international.desc': 'Sante care goes beyond geographical limits. With our VUMI International solution, we guarantee access to the most prestigious medical centers in the world.',
    'international.cta': 'Explore VUMI',
    'international.families': '+500 Families Protected',
    'international.feature1': 'Second Medical Opinion',
    'international.feature2': 'Worldwide Free Choice',
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'The trust of those who live the difference.',
    'testimonials.desc': 'Our greatest reward is our clients\' peace of mind. See what they say about Sante\'s care and performance.',
    'contact.badge': 'Priority Contact',
    'contact.title': 'Talk to a specialist now.',
    'contact.desc': 'Specialists ready to assist you.',
    'form.name': 'Full name',
    'form.name.placeholder': 'How should we call you?',
    'form.email': 'Business email',
    'form.email.placeholder': 'contact@sante.com.br',
    'form.whatsapp': 'WhatsApp / Phone',
    'form.whatsapp.placeholder': '(11) 99999-9999',
    'form.message': 'Your request',
    'form.message.placeholder': 'Tell us a bit about what you are looking for...',
    'form.submit': 'Send Proposal',
    'form.submitting': 'Sending...',
    'form.success': '✓ Sent successfully!',
    'form.error': '× Error sending. Please try again.',
    'form.privacy': 'By sending, you agree to our privacy policy.',
    'footer.desc': 'Specialists in elevated protection. We offer intelligent solutions in health, life, and international insurance with a focus on excellence and care.',
    'footer.solutions': 'Our Solutions',
    'footer.institutional': 'Institutional',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.tagline': 'Elevating care with innovation',
    'corp.badge': 'Insurance for Businesses',
    'corp.title': 'Strategic protection for your greatest asset.',
    'corp.desc': 'Personalized consultancy and robust health and protection solutions, designed for companies seeking excellence and human capital valuation.',
    'corp.cta': 'REQUEST QUOTE',
    'corp.partners': '+150 Partner Companies',
    'corp.health.title': 'Corporate Health',
    'corp.health.desc': 'The most valued benefit by employees. We offer efficient management, cost reduction, and access to the best hospital networks for your team.',
    'corp.health.f1': 'Loss ratio management and BI for companies',
    'corp.health.f2': 'Premium referenced network and exclusive service',
    'corp.health.f3': 'Flexible models with or without co-participation',
    'corp.health.cta': 'ANALYZE MY PLAN',
    'corp.life.title': 'Group Life',
    'corp.life.desc': 'Security for your employees and compliance for your company. Flexible plans that meet collective agreements and protect the future of families.',
    'corp.life.f1': 'Compliance with collective bargaining agreements (CCT)',
    'corp.life.f2': 'Financial protection for employees and partners',
    'corp.life.f3': 'Exclusive assistance and simplified contracting',
    'corp.life.cta': 'SIMULATE BENEFIT',
    'corp.dental.title': 'Corporate Dental',
    'corp.dental.desc': 'Complete well-being for your team with reduced cost. A wide network and agile service to guarantee your company\'s best smile.',
    'corp.dental.f1': 'Low budget impact and high perceived value',
    'corp.dental.f2': 'National network with specialists in all areas',
    'corp.dental.f3': 'Fast contracting from 2 lives (MEI)',
    'corp.dental.cta': 'QUOTE NOW',
    'corp.form.badge': 'Corporate Consultancy',
    'corp.form.title': 'Optimize your benefits and protect your business.',
    'corp.form.desc': 'Fill in your company details and receive a personalized technical study from our specialists.',
    'ind.badge': 'Insurance for Individuals',
    'ind.title': 'Complete protection for you and your family.',
    'ind.desc': 'Personalized health, life, and dental solutions designed for those who value elevated care and peace of mind at all times.',
    'ind.cta': 'REQUEST QUOTE',
    'ind.lives': '+2,500 Lives Protected',
    'ind.health.title': 'Health Plan',
    'ind.health.desc': 'The care your health deserves, with access to the best hospitals and an excellent accredited network. Transparency and agility in service.',
    'ind.health.f1': 'Complete and comprehensive medical coverage',
    'ind.health.f2': 'High-performance hospital network',
    'ind.health.f3': 'Flexible options with or without co-participation',
    'ind.health.cta': 'QUICK QUOTE',
    'ind.life.title': 'Life Insurance',
    'ind.life.desc': 'Peace of mind for those you love. Our life insurance offers the necessary financial support to face unforeseen events with security.',
    'ind.life.f1': 'Solid financial protection for your family',
    'ind.life.f2': 'Full coverage in case of unforeseen events',
    'ind.life.f3': 'Total flexibility in choosing values',
    'ind.life.cta': 'SIMULATE PROTECTION',
    'ind.dental.title': 'Dental Plan',
    'ind.dental.desc': 'A healthy smile is the gateway to well-being. We offer low-cost plans with a wide accredited network.',
    'ind.dental.f1': 'Consultations, cleanings, and various procedures',
    'ind.dental.f2': 'Accredited network across the national territory',
    'ind.dental.f3': 'Excellent cost-benefit for you and dependents',
    'ind.dental.cta': 'QUICK QUOTE',
    'ind.form.badge': 'Online Quote',
    'ind.form.title': 'Start your journey to elevated care today.',
    'ind.form.desc': 'Fill in the details below and receive a personalized analysis from our specialists.',
    'ind.form.quick': 'Quick Shortcut',
    'ind.form.quick.desc': 'Don\'t want to fill out the form now? No problem! Send a quick message or attach your documents and we\'ll get in touch.',
    'ind.form.talk': 'Talk to Specialist',
    'ind.form.talk.desc': 'Request a quote through the contact form',
    'ind.form.upload': 'Send File',
    'ind.form.upload.desc': 'PDF, spreadsheet, or any document',
    'ind.form.step1': 'Contact Details',
    'ind.form.step2': 'What are you looking for?',
    'ind.form.step2.life': 'Life Insurance Details',
    'ind.form.step3': 'Contracting Profile',
    'ind.form.step4': 'Preferences',
    'ind.form.step5': 'Needs',
    'ind.form.step6': 'Finish',
    'ind.form.files': 'Attached files:',
    'form.back': 'Back',
    'form.next': 'Next Step',
    'form.submitStudy': 'Send for Study',
    'form.successFull': '✓ Sent successfully! We will get in touch.',
    'corp.form.step1.title': 'Company Details',
    'corp.form.step1.desc': 'Tell us a bit about your business to get started.',
    'corp.form.step2.title': 'What does your company need?',
    'corp.form.step2.desc': 'You can select more than one option.',
    'corp.form.step3.title': 'General Information',
    'corp.form.step4.title': 'Company Profile',
    'corp.form.step5.title': 'Product Details',
    'corp.form.step5.desc': 'Let\'s customize your request based on your choices.',
    'corp.form.step6.title': 'Final Preferences',
    'corp.form.upload.title': 'File Upload (Optional)',
    'corp.form.upload.desc': 'If you already have a spreadsheet of lives or previous quotes, attach it here.',
    'corp.form.upload.optional': 'Optional Documents',
    'mascot.label': 'SANTÊ\'S TIP',
    'mascot.defaultMessage': 'Fill in as much as you want — the more information, the more precise and personalized your quote will be',
    'wa.message': 'Hello! I want to request a quote!',
    'cf.companyName': 'Company Name', 'cf.companyName.ph': 'Legal or Trade Name',
    'cf.cnpj': 'Tax ID (CNPJ)', 'cf.cnpj.ph': '00.000.000/0001-00',
    'cf.responsible': 'Contact Person', 'cf.responsible.ph': 'Who will talk to us?',
    'cf.email': 'Corporate Email', 'cf.email.ph': 'hr@company.com',
    'cf.whatsapp': 'Contact WhatsApp', 'cf.whatsapp.ph': '(11) 99999-9999',
    'cf.healthPlan': 'Health Plan', 'cf.lifeInsurance': 'Life Insurance', 'cf.dentalPlan': 'Dental Plan',
    'cf.startDate': 'Desired start date',
    'cf.hasBenefit': 'Does the company already have this benefit?',
    'cf.yes': 'Yes', 'cf.no': 'No', 'cf.which': 'Which?',
    'cf.which.ph': 'Ex: SulAmérica Health, Bradesco Dental...',
    'cf.employees': 'Number of Employees', 'cf.employees.ph': 'Ex: 50',
    'cf.cityState': 'City / State', 'cf.cityState.ph': 'Ex: São Paulo / SP',
    'cf.segment': 'Company Segment', 'cf.segment.ph': 'Ex: Technology, Industry, Commerce...',
    'cf.noProducts': 'You did not select any product in Step 2.',
    'cf.life.title': 'Life Insurance', 'cf.life.coverageType': 'Coverage Type',
    'cf.life.perEmployee': 'Per Employee Value', 'cf.life.perEmployee.desc': 'Each life has a fixed insured capital.',
    'cf.life.global': 'Global Value', 'cf.life.global.desc': 'Capital divided among employees.',
    'cf.life.accidents': 'Personal Accidents', 'cf.life.accidents.desc': 'Specific coverage for accidents.',
    'cf.life.spouses': 'Include spouses?', 'cf.life.absent': 'Employee on leave?',
    'cf.life.capitalDef': 'Capital Definition (Value)', 'cf.life.selectOption': 'Select an option...',
    'cf.life.equalAll': 'Equal for all', 'cf.life.salaryBased': 'Salary Multiple (e.g. 12x or 24x)',
    'cf.life.byPosition': 'Differentiated by position',
    'cf.health.title': 'Health Plan', 'cf.health.samePlan': 'All employees on the same plan?',
    'cf.health.samePlan.note': 'If "No", we will split the group by categories (e.g. Management vs. Operations).',
    'cf.health.accommodation': 'Accommodation Type', 'cf.health.select': 'Select...',
    'cf.health.ward': 'Ward (Shared)', 'cf.health.apartment': 'Private Room',
    'cf.health.copart': 'Co-participation', 'cf.health.noCopart': 'No Co-participation',
    'cf.health.withCopart': 'With Co-participation', 'cf.health.copartLimit': 'Co-participation Limit (%)',
    'cf.health.copartRecommend': 'Usually recommended: 20% or 30%.',
    'cf.dental.title': 'Corporate Dental', 'cf.dental.hasPlan': 'Already have a Dental Plan?',
    'cf.dental.currentProvider': 'Current provider?', 'cf.dental.currentProvider.ph': 'Ex: Amil Dental, OdontoPrev...',
    'cf.objective': 'What is the main objective of this quote?',
    'cf.reduceCosts': 'Reduce Costs', 'cf.betterCoverage': 'Better Coverage', 'cf.retainTalent': 'Retain Talent',
    'cf.upgradeLevel': 'Desired Upgrade Level',
    'cf.basic': 'Basic (Price focused)', 'cf.intermediate': 'Intermediate (Cost-benefit)',
    'cf.premium': 'Premium (High coverage and reimbursement)',
    'cf.additionalServices': 'Desired Additional Services',
    'cf.reimbursement': 'Free Choice (Reimbursement)', 'cf.concierge': 'Concierge Service',
    'cf.airRescue': 'Air Medical Rescue',
    'cf.hospitals': 'Mandatory Hospitals or Labs?', 'cf.hospitals.ph': 'Ex: Albert Einstein, Sírio Libanês, Fleury...',
    'pf.step1': 'Contact Details', 'pf.fullName': 'Full Name', 'pf.fullName.ph': 'Your name',
    'pf.email': 'Email', 'pf.email.ph': 'your@email.com',
    'pf.whatsapp': 'WhatsApp', 'pf.whatsapp.ph': '(11) 99999-9999',
    'pf.step2': 'What are you looking for?',
    'pf.healthPlan': 'Health Plan', 'pf.lifeInsurance': 'Life Insurance', 'pf.dentalPlan': 'Dental Plan',
    'pf.lifeDetails': 'Life Insurance Details',
    'pf.dob': 'Date of Birth', 'pf.sex': 'Gender', 'pf.select': 'Select...',
    'pf.male': 'Male', 'pf.female': 'Female',
    'pf.occupation': 'Occupation', 'pf.occupation.ph': 'Ex: Engineer, Doctor...',
    'pf.income': 'Income Range',
    'pf.step3': 'Contracting Profile', 'pf.planType': 'Plan Type',
    'pf.individual': 'Individual', 'pf.family': 'Family',
    'pf.location': 'Location', 'pf.location.ph': 'City/Region',
    'pf.lives': 'Number of Lives', 'pf.lives.ph': 'Ex: 5',
    'pf.ages': 'Ages of people', 'pf.ages.ph': 'Ex: 25, 30, 2',
    'pf.step4': 'Preferences', 'pf.copart': 'Co-participation',
    'pf.indifferent': 'Indifferent', 'pf.yes': 'Yes', 'pf.no': 'No',
    'pf.accommodation': 'Accommodation', 'pf.apartment': 'Private Room', 'pf.ward': 'Ward',
    'pf.coverage': 'Coverage Area', 'pf.regional': 'Regional', 'pf.national': 'National', 'pf.international': 'International',
    'pf.priority': 'What is most important to you?',
    'pf.lowCost': 'Low monthly cost', 'pf.bestNetwork': 'Best hospital network', 'pf.costQuality': 'Cost vs. Quality',
    'pf.hospitals': 'Must-have hospitals', 'pf.hospitals.ph': 'Ex: Albert Einstein, Sírio-Libanês, etc...',
    'pf.step5': 'Needs', 'pf.frequency': 'Usage frequency',
    'pf.low': 'Low', 'pf.medium': 'Medium', 'pf.high': 'High',
    'pf.desiredCoverage': 'Desired coverages',
    'pf.therapy': 'Therapy', 'pf.physio': 'Physiotherapy', 'pf.maternity': 'Maternity',
    'pf.step6': 'Finish', 'pf.upload': 'File Upload (Optional)',
    'pf.upload.desc': 'If you are MEI or have multiple lives, attach a PDF or spreadsheet.',
    'pf.files': 'Attached files:',
    'pf.importantNote': 'Anything important we should know?', 'pf.importantNote.ph': 'Your message...',
    'pf.submitAnalysis': 'Send for analysis'
  },
  fr: {
    'nav.about': 'À Propos',
    'nav.solutions': 'SOLUTIONS',
    'nav.contact': 'Contact',
    'nav.quote': 'Devis en Ligne',
    'nav.company': 'Entreprise',
    'nav.people': 'Individuel',
    'nav.forCompany': 'Pour Entreprise',
    'nav.forYou': 'Pour Vous',
    'sol.health': 'Santé',
    'sol.life': 'Vie',
    'sol.dental': 'Dentaire',
    'sol.international': 'International',
    'sol.person': 'Individuel',
    'hero.title.business': 'Assurance pour Entreprises',
    'hero.desc.business': 'Conseil personnalisé pour votre entreprise, avec innovation et cyber-intelligence.',
    'hero.title.people': 'Assurance pour Particuliers',
    'hero.desc.people': 'Protection complète pour vous et votre famille, axée sur des soins de qualité et la tranquillité d\'esprit.',
    'hero.learnMore': 'EN SAVOIR PLUS',
    'about.badge': 'À PROPOS',
    'about.title': 'Votre santé mérite des soins de qualité.',
    'about.desc': 'Sante est un courtier de haute performance, offrant les meilleures solutions en assurance santé, vie et internationale avec un accent total sur la protection et l\'innovation depuis 20 ans.',
    'about.regional': 'Régional',
    'about.regional.desc': 'Meilleures options locales.',
    'about.national': 'National',
    'about.national.desc': 'Couverture nationale.',
    'about.global': 'Mondial',
    'about.global.desc': 'Service dans le monde entier.',
    'partners.badge': 'Réseau d\'Excellence',
    'partners.title': 'Compagnies d\'Assurances Partenaires',
    'international.badge': 'Portée Mondiale',
    'international.title': 'Votre protection ne connaît pas de frontières.',
    'international.desc': 'Le soin Sante dépasse les limites géographiques. Avec notre solution VUMI International, nous garantissons l\'accès aux centres médicaux les plus prestigieux du monde.',
    'international.cta': 'Explorer VUMI',
    'international.families': '+500 Familles Protégées',
    'international.feature1': 'Deuxième Avis Médical',
    'international.feature2': 'Libre Choix Mondial',
    'testimonials.badge': 'Témoignages',
    'testimonials.title': 'La confiance de ceux qui vivent la différence.',
    'testimonials.desc': 'Notre plus belle récompense est la tranquillité d\'esprit de nos clients. Voyez ce qu\'ils disent des soins et des performances de Sante.',
    'contact.badge': 'Contact Prioritaire',
    'contact.title': 'Parlez à un spécialiste maintenant.',
    'contact.desc': 'Des spécialistes prêts à vous aider.',
    'form.name': 'Nom complet',
    'form.name.placeholder': 'Comment devrions-nous vous appeler ?',
    'form.email': 'E-mail professionnel',
    'form.email.placeholder': 'contact@sante.com.br',
    'form.whatsapp': 'WhatsApp / Téléphone',
    'form.whatsapp.placeholder': '(11) 99999-9999',
    'form.message': 'Votre demande',
    'form.message.placeholder': 'Dites-nous en un peu plus sur ce que vous recherchez...',
    'form.submit': 'Envoyer la Proposition',
    'form.submitting': 'Envoi en cours...',
    'form.success': '✓ Envoyé avec succès !',
    'form.error': '× Erreur lors de l\'envoi. Veuillez réessayer.',
    'form.privacy': 'En envoyant, vous acceptez notre politique de confidentialité.',
    'footer.desc': 'Spécialistes de la protection de haut niveau. Nous proposons des solutions intelligentes en assurance santé, vie et internationale avec un accent sur l\'excellence et le soin.',
    'footer.solutions': 'Nos Solutions',
    'footer.institutional': 'Institutionnel',
    'footer.contact': 'Contactez-nous',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.tagline': 'Élever le soin avec l\'innovation',
    'corp.badge': 'Assurance pour Entreprises',
    'corp.title': 'Protection stratégique pour votre plus grand atout.',
    'corp.desc': 'Conseil personnalisé et solutions de santé et de protection robustes, conçus pour les entreprises recherchant l\'excellence et la valorisation du capital humain.',
    'corp.cta': 'DEMANDER UN DEVIS',
    'corp.partners': '+150 Entreprises Partenaires',
    'corp.health.title': 'Santé en Entreprise',
    'corp.health.desc': 'L\'avantage le plus apprécié par les salariés. Nous proposons une gestion efficace, une réduction des coûts et un accès aux meilleurs réseaux hospitaliers pour votre équipe.',
    'corp.health.f1': 'Gestion du taux de sinistralité et BI pour les entreprises',
    'corp.health.f2': 'Réseau de référence premium et service exclusif',
    'corp.health.f3': 'Modèles flexibles avec ou sans coparticipation',
    'corp.health.cta': 'ANALYSER MON PLAN',
    'corp.life.title': 'Vie de Groupe',
    'corp.life.desc': 'Sécurité pour vos salariés et conformité pour votre entreprise. Des plans flexibles qui répondent aux conventions collectives et protègent l\'avenir des familles.',
    'corp.life.f1': 'Respect des conventions collectives (CCT)',
    'corp.life.f2': 'Protection financière des salariés et des associés',
    'corp.life.f3': 'Assistance exclusive et souscription simplifiée',
    'corp.life.cta': 'SIMULER L\'AVANTAGE',
    'corp.dental.title': 'Dentaire en Entreprise',
    'corp.dental.desc': 'Un bien-être complet pour votre équipe à coût réduit. Un réseau large et un service agile pour garantir le meilleur sourire de votre entreprise.',
    'corp.dental.f1': 'Faible impact budgétaire et haute valeur perçue',
    'corp.dental.f2': 'Réseau national avec des spécialistes dans tous les domaines',
    'corp.dental.f3': 'Contractualisation rapide à partir de 2 vies (MEI)',
    'corp.dental.cta': 'DEVIS MAINTENANT',
    'corp.form.badge': 'Conseil aux Entreprises',
    'corp.form.title': 'Optimisez vos avantages et protégez votre entreprise.',
    'corp.form.desc': 'Remplissez les coordonnées de votre entreprise et recevez une étude technique personnalisée de nos spécialistes.',
    'ind.badge': 'Assurance pour Particuliers',
    'ind.title': 'Protection complète pour vous et votre famille.',
    'ind.desc': 'Des solutions de santé, de vie et dentaires personnalisées conçues pour ceux qui apprécient les soins de qualité et la tranquillité d\'esprit à tout moment.',
    'ind.cta': 'DEMANDER UN DEVIS',
    'ind.lives': '+2 500 Vies Protégées',
    'ind.health.title': 'Plan de Santé',
    'ind.health.desc': 'Les soins que votre santé mérite, avec un accès aux meilleurs hôpitaux et un excellent réseau agréé. Transparence et agilité au service.',
    'ind.health.f1': 'Couverture médicale complète et globale',
    'ind.health.f2': 'Réseau hospitalier de haute performance',
    'ind.health.f3': 'Options flexibles avec ou sans coparticipation',
    'ind.health.cta': 'DEVIS RAPIDE',
    'ind.life.title': 'Assurance Vie',
    'ind.life.desc': 'Tranquillité d\'esprit pour ceux que vous aimez. Notre assurance vie offre le soutien financier nécessaire pour faire face aux imprévus en toute sécurité.',
    'ind.life.f1': 'Une protection financière solide pour votre famille',
    'ind.life.f2': 'Couverture complète en cas d\'imprevus',
    'ind.life.f3': 'Flexibilité totale dans le choix des valeurs',
    'ind.life.cta': 'SIMULER LA PROTECTION',
    'ind.dental.title': 'Plan Dentaire',
    'ind.dental.desc': 'Un sourire sain est la porte d\'entrée du bien-être. Nous proposons des forfaits à bas prix avec un large réseau agréé.',
    'ind.dental.f1': 'Consultations, nettoyages et procédures diverses',
    'ind.dental.f2': 'Réseau agréé sur tout le territoire national',
    'ind.dental.f3': 'Excellent rapport coût-bénéfice pour vous et vos dépendants',
    'ind.dental.cta': 'DEVIS RAPIDE',
    'ind.form.badge': 'Devis en Ligne',
    'ind.form.title': 'Commencez dès aujourd\'hui votre voyage vers des soins de qualité.',
    'ind.form.desc': 'Remplissez les détails ci-dessous et recevez une analyse personnalisée de nos spécialistes.',
    'ind.form.quick': 'Raccourci Rapide',
    'ind.form.quick.desc': 'Vous ne voulez pas remplir le formulaire maintenant ? Aucun problème ! Envoyez um message rapide ou joignez vos documents et nous vous contacterons.',
    'ind.form.talk': 'Parler à um Spécialiste',
    'ind.form.talk.desc': 'Demander un devis via le formulaire de contact',
    'ind.form.upload': 'Envoyer un Fichier',
    'ind.form.upload.desc': 'PDF, tableur ou tout document',
    'ind.form.step1': 'Coordonnées de Contact',
    'ind.form.step2': 'Que recherchez-vous ?',
    'ind.form.step2.life': 'Détails de l\'Assurance Vie',
    'ind.form.step3': 'Profil de Contractualisation',
    'ind.form.step4': 'Préférences',
    'ind.form.step5': 'Besoins',
    'ind.form.step6': 'Terminer',
    'ind.form.files': 'Fichiers joints :',
    'form.back': 'Retour',
    'form.next': 'Étape Suivante',
    'form.submitStudy': 'Envoyer pour Étude',
    'form.successFull': '✓ Envoyé avec succès ! Nous vous contacterons.',
    'corp.form.step1.title': 'Détails de l\'Entreprise',
    'corp.form.step1.desc': 'Parlez-nous un peu de votre entreprise pour commencer.',
    'corp.form.step2.title': 'De quoi votre entreprise a-t-elle besoin ?',
    'corp.form.step2.desc': 'Vous pouvez sélectionner plus d\'une option.',
    'corp.form.step3.title': 'Informations Générales',
    'corp.form.step4.title': 'Profil de l\'Entreprise',
    'corp.form.step5.title': 'Détails du Produit',
    'corp.form.step5.desc': 'Personnalisons votre demande en fonction de vos choix.',
    'corp.form.step6.title': 'Préférences Finales',
    'corp.form.upload.title': 'Téléchargement de fichier (Optionnel)',
    'corp.form.upload.desc': 'Si vous avez déjà un tableur de vies ou des devis précédents, joignez-le ici.',
    'corp.form.upload.optional': 'Documents Optionnels',
    'mascot.label': 'CONSEIL DE SANTÊ',
    'mascot.defaultMessage': 'Remplissez autant que vous le souhaitez — plus vous donnez d\'informations, plus votre devis sera précis et personnalisé',
    'wa.message': 'Bonjour ! Je souhaite demander un devis !',
    'cf.companyName': 'Nom de l\'Entreprise', 'cf.companyName.ph': 'Raison sociale ou nom commercial',
    'cf.cnpj': 'N° SIRET', 'cf.cnpj.ph': '00.000.000/0001-00',
    'cf.responsible': 'Nom du Responsable', 'cf.responsible.ph': 'Qui nous contactera ?',
    'cf.email': 'E-mail Professionnel', 'cf.email.ph': 'rh@entreprise.com',
    'cf.whatsapp': 'WhatsApp de Contact', 'cf.whatsapp.ph': '(11) 99999-9999',
    'cf.healthPlan': 'Plan de Santé', 'cf.lifeInsurance': 'Assurance Vie', 'cf.dentalPlan': 'Plan Dentaire',
    'cf.startDate': 'Date de début souhaitée',
    'cf.hasBenefit': 'L\'entreprise possède-t-elle déjà cet avantage ?',
    'cf.yes': 'Oui', 'cf.no': 'Non', 'cf.which': 'Lequel ?',
    'cf.which.ph': 'Ex : SulAmérica Santé, Bradesco Dentaire...',
    'cf.employees': 'Nombre de Salariés', 'cf.employees.ph': 'Ex : 50',
    'cf.cityState': 'Ville / État', 'cf.cityState.ph': 'Ex : São Paulo / SP',
    'cf.segment': 'Secteur d\'Activité', 'cf.segment.ph': 'Ex : Technologie, Industrie, Commerce...',
    'cf.noProducts': 'Vous n\'avez sélectionné aucun produit à l\'Étape 2.',
    'cf.life.title': 'Assurance Vie', 'cf.life.coverageType': 'Type de Couverture',
    'cf.life.perEmployee': 'Valeur par Salarié', 'cf.life.perEmployee.desc': 'Chaque vie a un capital assuré fixe.',
    'cf.life.global': 'Valeur Globale', 'cf.life.global.desc': 'Capital réparti entre les salariés.',
    'cf.life.accidents': 'Accidents Personnels', 'cf.life.accidents.desc': 'Couverture spécifique pour les accidents.',
    'cf.life.spouses': 'Inclure les conjoints ?', 'cf.life.absent': 'Salarié en congé ?',
    'cf.life.capitalDef': 'Définition du Capital (Valeur)', 'cf.life.selectOption': 'Sélectionner une option...',
    'cf.life.equalAll': 'Égal pour tous', 'cf.life.salaryBased': 'Multiple Salarial (ex : 12x ou 24x)',
    'cf.life.byPosition': 'Différencié par poste',
    'cf.health.title': 'Plan de Santé', 'cf.health.samePlan': 'Tous les salariés sur le même plan ?',
    'cf.health.samePlan.note': 'Si \"Non\", nous diviserons le groupe par catégories (ex : Direction vs. Opérations).',
    'cf.health.accommodation': 'Type d\'Hébergement', 'cf.health.select': 'Sélectionner...',
    'cf.health.ward': 'Chambre Partagée', 'cf.health.apartment': 'Chambre Privée',
    'cf.health.copart': 'Coparticipation', 'cf.health.noCopart': 'Sans Coparticipation',
    'cf.health.withCopart': 'Avec Coparticipation', 'cf.health.copartLimit': 'Limite de Coparticipation (%)',
    'cf.health.copartRecommend': 'Généralement recommandé : 20% ou 30%.',
    'cf.dental.title': 'Dentaire en Entreprise', 'cf.dental.hasPlan': 'Possédez-vous déjà un Plan Dentaire ?',
    'cf.dental.currentProvider': 'Opérateur actuel ?', 'cf.dental.currentProvider.ph': 'Ex : Amil Dental, OdontoPrev...',
    'cf.objective': 'Quel est l\'objectif principal de ce devis ?',
    'cf.reduceCosts': 'Réduire les Coûts', 'cf.betterCoverage': 'Meilleure Couverture', 'cf.retainTalent': 'Fidéliser les Talents',
    'cf.upgradeLevel': 'Niveau de Mise à Jour Souhaité',
    'cf.basic': 'Basique (Axé sur le prix)', 'cf.intermediate': 'Intermédiaire (Rapport qualité-prix)',
    'cf.premium': 'Premium (Haute couverture et remboursement)',
    'cf.additionalServices': 'Services Additionnels Souhaités',
    'cf.reimbursement': 'Libre Choix (Remboursement)', 'cf.concierge': 'Service Conciergerie',
    'cf.airRescue': 'Rapatriement Aéromédical',
    'cf.hospitals': 'Hôpitaux ou Laboratoires Obligatoires ?', 'cf.hospitals.ph': 'Ex : Albert Einstein, Sírio Libanês, Fleury...',
    'pf.step1': 'Coordonnées de Contact', 'pf.fullName': 'Nom Complet', 'pf.fullName.ph': 'Votre nom',
    'pf.email': 'E-mail', 'pf.email.ph': 'votre@email.com',
    'pf.whatsapp': 'WhatsApp', 'pf.whatsapp.ph': '(11) 99999-9999',
    'pf.step2': 'Que recherchez-vous ?',
    'pf.healthPlan': 'Plan de Santé', 'pf.lifeInsurance': 'Assurance Vie', 'pf.dentalPlan': 'Plan Dentaire',
    'pf.lifeDetails': 'Détails de l\'Assurance Vie',
    'pf.dob': 'Date de Naissance', 'pf.sex': 'Sexe', 'pf.select': 'Sélectionner...',
    'pf.male': 'Masculin', 'pf.female': 'Féminin',
    'pf.occupation': 'Profession', 'pf.occupation.ph': 'Ex : Ingénieur, Médecin...',
    'pf.income': 'Tranche de Revenus',
    'pf.step3': 'Profil de Contractualisation', 'pf.planType': 'Type de Plan',
    'pf.individual': 'Individuel', 'pf.family': 'Familial',
    'pf.location': 'Localisation', 'pf.location.ph': 'Ville/Région',
    'pf.lives': 'Nombre de Vies', 'pf.lives.ph': 'Ex : 5',
    'pf.ages': 'Âges des personnes', 'pf.ages.ph': 'Ex : 25, 30, 2',
    'pf.step4': 'Préférences', 'pf.copart': 'Coparticipation',
    'pf.indifferent': 'Indifférent', 'pf.yes': 'Oui', 'pf.no': 'Non',
    'pf.accommodation': 'Hébergement', 'pf.apartment': 'Chambre Privée', 'pf.ward': 'Chambre Partagée',
    'pf.coverage': 'Couverture', 'pf.regional': 'Régionale', 'pf.national': 'Nationale', 'pf.international': 'Internationale',
    'pf.priority': 'Qu\'est-ce qui est le plus important pour vous ?',
    'pf.lowCost': 'Mensualité basse', 'pf.bestNetwork': 'Meilleur réseau hospitalier', 'pf.costQuality': 'Coût vs. Qualité',
    'pf.hospitals': 'Hôpitaux indispensables', 'pf.hospitals.ph': 'Ex : Albert Einstein, Sírio-Libanês, etc...',
    'pf.step5': 'Besoins', 'pf.frequency': 'Fréquence d\'utilisation',
    'pf.low': 'Basse', 'pf.medium': 'Moyenne', 'pf.high': 'Élevée',
    'pf.desiredCoverage': 'Couvertures souhaitées',
    'pf.therapy': 'Thérapie', 'pf.physio': 'Kinésithérapie', 'pf.maternity': 'Maternité',
    'pf.step6': 'Terminer', 'pf.upload': 'Téléchargement de fichier (Optionnel)',
    'pf.upload.desc': 'Si vous êtes MEI ou avez plusieurs vies, joignez un PDF ou un tableur.',
    'pf.files': 'Fichiers joints :',
    'pf.importantNote': 'Quelque chose d\'important à nous signaler ?', 'pf.importantNote.ph': 'Votre message...',
    'pf.submitAnalysis': 'Envoyer pour analyse'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'pt' || savedLang === 'en' || savedLang === 'fr')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
